import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { parseDocument } from "yaml";

import { renderDraftLineageComment } from "../../src/promote/draft-lineage.ts";
import { customTags } from "../../src/schema/tags.ts";

interface AmendmentLike {
	before?: string;
}

interface CriterionLike {
	id: string;
	statement: string;
	amendments?: AmendmentLike[];
}

interface NodeLike {
	acceptance?: CriterionLike[];
	work?: NodeLike[];
}

interface DraftLineageOptions {
	cwd?: string;
	draftPath?: string;
	draftSource?: string;
}

function criteriaIn(source: string): CriterionLike[] {
	const document = parseDocument(source, { customTags });
	if (document.errors.length > 0) return [];
	const value = document.toJS() as { work?: NodeLike[] } | undefined;
	const criteria: CriterionLike[] = [];
	function visit(nodes: readonly NodeLike[] | undefined): void {
		for (const node of nodes ?? []) {
			criteria.push(...(node.acceptance ?? []));
			visit(node.work);
		}
	}
	visit(value?.work);
	return criteria;
}

function renderStatement(id: string, statement: string): string {
	const lines = statement.split("\n");
	return [`- ${id}: ${lines[0]}`, ...lines.slice(1).map((line) => line.length === 0 ? "" : `  ${line}`)].join("\n");
}

/** Build the draft that would have promoted the current fixture's first lineage links. */
export function draftSourceForWorkspec(source: string): string {
	const criteria = criteriaIn(source);
	return [
		"## Acceptance criteria <!-- work:criteria -->",
		...criteria.map((criterion) => renderStatement(criterion.id, criterion.amendments?.[0]?.before ?? criterion.statement)),
		"",
	].join("\n");
}

function persistedDraftPath(draftSource: string, cwd: string): string {
	const digest = createHash("sha256").update(draftSource, "utf8").digest("hex");
	const directory = path.join(cwd, ".test-dist", "test-drafts", String(process.pid));
	mkdirSync(directory, { recursive: true });
	const draftPath = path.join(directory, `${digest}.md`);
	writeFileSync(draftPath, draftSource, "utf8");
	return path.relative(cwd, draftPath).replaceAll(path.sep, "/");
}

/** Add the visible promotion comment and materialize its draft for validation tests. */
export function withDraftLineage(source: string, options: DraftLineageOptions = {}): string {
	if (source.startsWith("# Generated by work_promote from ") && Object.keys(options).length === 0) return source;
	const unframed = source.startsWith("# Generated by work_promote from ") ? source.slice(source.indexOf("\n") + 1) : source;
	const draftSource = options.draftSource ?? draftSourceForWorkspec(unframed);
	const cwd = options.cwd ?? process.cwd();
	const draftPath = options.draftPath ?? persistedDraftPath(draftSource, cwd);
	return `${renderDraftLineageComment(draftPath)}\n${unframed}`;
}
