#!/usr/bin/env node
// Generate Bend enum types with key, parse, code and proofs.
//
// Usage: node gen-enums.mjs spec.json > Enums.bend
//
// spec.json:
//   { "enums": [ { "name": "Owner", "cases": [
//       { "ctor": "WAbsent", "key": "owner-absent" }, ... ] } ] }
//
// For each enum E the output has:
//   type E, E.key(x) -> String, E.parse(s) -> E, E.code(x) -> Nat,
//   E.all() -> List<&2, E>,
//   law E.parse_key: parse(key(x)) == x          (so key is injective)
//   law E.key_injective: key(a) == key(b) -> a == b
//   law E.all_nodup: all() has no duplicates     (via Lib.sortedC_sound; codes ascend)
//   law E.all_complete: every value is in all()
//   law E.take_key: take(key(x) ++ ":" ++ r) == (x, r), when no key has ':'
//     (feeds Lib.join_injective for composite keys)
// The output imports ./Lib.bend as L. Keys must be distinct and non-empty,
// and must not contain the separator you later join them with.
import { cli, json, unavailable, verifyHeaders } from './intent-core.mjs';

const NAME = /^[A-Z][A-Za-z0-9_]*$/;

export function validate(spec) {
	if (!spec || !Array.isArray(spec.enums) || spec.enums.length === 0) throw new Error("spec.enums must be a non-empty array");
	const ctors = new Set();
	const names = new Set();
	for (const e of spec.enums) {
		if (!NAME.test(e?.name ?? "")) throw new Error(`bad enum name ${JSON.stringify(e?.name)}`);
		if (names.has(e.name)) throw new Error(`duplicate enum ${e.name}`);
		names.add(e.name);
		if (!Array.isArray(e.cases) || e.cases.length === 0) throw new Error(`${e.name}: cases must be a non-empty array`);
		const keys = new Set();
		for (const c of e.cases) {
			if (!NAME.test(c?.ctor ?? "")) throw new Error(`${e.name}: bad constructor ${JSON.stringify(c?.ctor)}`);
			if (ctors.has(c.ctor)) throw new Error(`${e.name}: constructor ${c.ctor} is already used`);
			ctors.add(c.ctor);
			if (typeof c.key !== "string" || c.key.length === 0) throw new Error(`${e.name}.${c.ctor}: key must be a non-empty string`);
			if (/["\\\n]/.test(c.key)) throw new Error(`${e.name}.${c.ctor}: key must not contain quotes, backslashes or newlines`);
			if (keys.has(c.key)) throw new Error(`${e.name}: duplicate key ${JSON.stringify(c.key)}`);
			keys.add(c.key);
		}
	}
	return spec;
}

function caseSplit(e, indent, body) {
	const lines = [`${indent}match x:`];
	for (const c of e.cases) lines.push(`${indent}  case ${c.ctor}{}:`, `${indent}    ${body(c)}`);
	return lines.join("\n");
}

function parseChain(e) {
	// The first case is the fallback, so every string parses to some value.
	const [first, ...rest] = e.cases;
	let expr = `${first.ctor}{}`;
	for (const c of [...rest].reverse()) expr = `Bool.pick(${e.name}, String.eq(s, "${c.key}"), ${c.ctor}{}, ${expr})`;
	return expr;
}

export function generate(spec) {
	validate(spec);
	const out = ["# Generated by gen-enums.mjs. Do not edit by hand; edit the spec and regenerate.", "import Base", "import ./Lib.bend as L", ""];
	for (const e of spec.enums) {
		const n = e.name;
		out.push(`type ${n} is Data:`, ...e.cases.map((c) => `  ${c.ctor}{}`), "");
		out.push(`def ${n}.key(x: ${n}) -> String:`, caseSplit(e, "  ", (c) => `"${c.key}"`), "");
		out.push(`def ${n}.parse(+s: String) -> ${n}:`, `  ${parseChain(e)}`, "");
		out.push(`def ${n}.code(x: ${n}) -> Nat:`, caseSplit(e, "  ", (c) => `${e.cases.indexOf(c)}n`), "");
		out.push(`def ${n}.all() -> List<&2, ${n}>:`, `  [${e.cases.map((c) => `${c.ctor}{}`).join(", ")}]`, "");
		out.push(`law ${n}.parse_key:`, `  for x: ${n}`, `  {${n}.parse(${n}.key(x)) == x : ${n}}`, "");
		out.push(`def ${n}.parse_key(x):`, caseSplit(e, "  ", () => "{==}"), "");
		out.push(
			`law ${n}.key_injective:`,
			`  for a: ${n}`,
			`  for b: ${n}`,
			`  for e: {${n}.key(a) == ${n}.key(b) : String}`,
			`  {a == b : ${n}}`,
			"",
			`def ${n}.key_injective(a, b, e):`,
			`  %${n}.parse_key(a) : {_ == b : ${n}}`,
			`  %${n}.parse_key(b) : {${n}.parse(${n}.key(a)) == _ : ${n}}`,
			`  %e : {${n}.parse(${n}.key(a)) == ${n}.parse(_) : ${n}}`,
			"  {==}",
			"",
		);
		out.push(`law ${n}.all_nodup:`, `  L.Nodup(${n}, ${n}.all())`, "", `def ${n}.all_nodup():`, `  L.sortedC_sound(~${n}, ~${n}.code, ${n}.all(), Unit{})`, "");
		out.push(`law ${n}.all_complete:`, `  for x: ${n}`, `  L.Mem(${n}, x, ${n}.all())`, "", `def ${n}.all_complete(x):`, caseSplit(e, "  ", (c) => { const i = e.cases.indexOf(c); return `${"Inr{".repeat(i)}Inl{{==}}${"}".repeat(i)}`; }), "");
		if (e.cases.every((c) => !c.key.includes(":"))) {
			out.push(
				`law ${n}.take_key:`,
				`  for x: ${n}`,
				"  for r: String",
				`  {L.take(~${n}, ~${n}.parse, ${n}.key(x) ++ (":" ++ r)) == (x, r) : ${n} & String}`,
				"",
				`def ${n}.take_key(x, r):`,
				caseSplit(e, "  ", () => "{==}"),
				"",
			);
		}
	}
	return `${out.join("\n").trimEnd()}\n`;
}

await cli(argv => {
	verifyHeaders(import.meta.url);
	if (argv.length !== 1) unavailable('gen-enums: usage: gen-enums.mjs spec.json > Enums.bend; supply an enum specification');
	try { process.stdout.write(generate(json(argv[0]))); }
	catch (error) { unavailable(`gen-enums: ${error.message}; fix the enum specification`); }
}, import.meta.url);
