import assert from "node:assert/strict";
import test from "node:test";

import { referencedDraftPath, renderDraftLineageComment } from "../../src/promote/index.ts";

test("draft lineage comments round-trip visible paths with spaces and punctuation", () => {
	const draftPath = ".work/drafts/spec #14; amendment (final).md";
	const comment = renderDraftLineageComment(draftPath);
	assert.equal(comment, `# Generated by work_promote from ${draftPath}; decompose before approval.`);
	assert.equal(referencedDraftPath(`${comment}\ntitle: spec\n`), draftPath);
	assert.equal(referencedDraftPath(`# Generated by work_promote from ${draftPath}; decomposed against issue #14.\ntitle: spec\n`), draftPath);
});

test("draft lineage comments keep newline metadata on one line and reject malformed pointers", () => {
	const comment = renderDraftLineageComment("draft.md\ninjected: true");
	assert.equal(comment.split("\n").length, 1);
	assert.equal(referencedDraftPath(`${comment}\ntitle: spec\n`), "draft.md\\ninjected: true");
	for (const source of [
		"title: no lineage\n",
		"# Generated by work_promote from ; decompose before approval.\ntitle: empty\n",
		"# Generated by work_promote from draft.md without delimiter\ntitle: malformed\n",
		"title: spec\n# Generated by work_promote from late.md; decompose before approval.\n",
	]) assert.equal(referencedDraftPath(source), undefined);
});
