const COMMENT_PREFIX = "# Generated by work_promote from ";
const COMMENT_SUFFIX = "; decompose before approval.";

function oneLinePath(sourcePath: string): string {
	return sourcePath.replaceAll("\\", "/").replace(/\r\n|\r|\n/g, "\\n");
}

/** Render the visible pointer from a workspec to the draft that promotion consumed. */
export function renderDraftLineageComment(sourcePath: string): string {
	return `${COMMENT_PREFIX}${oneLinePath(sourcePath)}${COMMENT_SUFFIX}`;
}

/**
 * Read the visible draft pointer retained by promotion and later decomposition.
 * This pointer is not absolute authentication: changing the authored draft prose
 * or repointing this conspicuous first line changes the lineage anchor. Reviewers
 * must inspect either change.
 */
export function referencedDraftPath(specSource: string): string | undefined {
	const firstLine = specSource.split(/\r\n|\r|\n/, 1)[0];
	if (!firstLine.startsWith(COMMENT_PREFIX)) return undefined;
	const match = /^# Generated by work_promote from (.*); decompos(?:e|ed)\b/.exec(firstLine);
	return match?.[1] ? match[1] : undefined;
}
